# Generated by Django 2.2.4 on 2019-08-25 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(verbose_name='data emprestimo')),
                ('data_devolução', models.DateTimeField(verbose_name='data devolucao')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Usuario')),
            ],
        ),
    ]
