# Generated by Django 2.2.4 on 2019-08-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('localizacao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=20)),
                ('codigo_sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Sessao')),
                ('emprestimo', models.ManyToManyField(to='biblioteca.Emprestimo')),
            ],
        ),
    ]
